[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.18.16" # Solana version to use

[features]
seeds = false
skip-lint = false

[programs.localnet]
multisig = "5XyhmmQ2dRFpnLtjbWZYkNH46YkEBzaKodnjTR7Cm9er"
versioned_squads_multisig_program = "5XyhmmQ2dRFpnLtjbWZYkNH46YkEBzaKodnjTR7Cm9er"

[programs.devnet]
multisig = "5XyhmmQ2dRFpnLtjbWZYkNH46YkEBzaKodnjTR7Cm9er"
versioned_squads_multisig_program = "5XyhmmQ2dRFpnLtjbWZYkNH46YkEBzaKodnjTR7Cm9er"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.account]]
address = "D3oQ6QxSYk6aKUsmBTa9BghFQvbRi7kxP6h95NSdjjXz"
filename = "tests/fixtures/pre-rent-collector/multisig-account.json"

[scripts]
test = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/index.ts"
